[package]
name = "renaissance-os"
version = "0.1.0"
authors = ["David Gonzalez Martin <davidgm94.work@protonmail.com"]

#[lib]
#crate-type = ["bin"]

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

[dependencies.bitflags]
version = "1.3.2"
