[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
[build]
target = "rust_target.json"
[rust]
channel = "nightly"
