[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
[build]
target = "rust_target.json"
#[profile.dev]
#panic = "abort"
#[profile.release]
#panic = "abort"
[rust]
channel = "nightly"
